exports.siRen = {
    haveRoom:0,
    type: "hainanmj",
    jushu: 0,
    wanfa: 0,
    mjType: 0,
    tg:0,
    func:false,
    otherData: {
        buchi: false,
        budianpao: false,
        goujiao: false,
        haidibao: true,
        huahu: true,
        lianzhuang: true,
        ling: true,
        liuju: true,
        mogangfan: false,
        ready: false,
        shangga: true,
        shangga3: false,
        shangga5: false,
        maxga3:false,
        fixga3:false,
        hunyise:true,
        sjzhuang: false,
        wuzi: false,
        zhuangxian: true,
        zyshangga: false,
    },
    coinData:{
       min:100,
       every:1,
       reduce:1,
       reduce_a:1,
       reduce_b:1,
    }
}
exports.sanRen = {
    haveRoom:0,
    type: "hainanmj",
    jushu: 0,
    wanfa: 0,
    mjType: 1,
    tg:0,
    func:false,
    otherData: {
        buchi: false,
        budianpao: false,
        goujiao: false,
        haidibao: true,
        huahu: true,
        lianzhuang: true,
        ling: true,
        liuju: true,
        mogangfan: false,
        ready: false,
        shangga: true,
        shangga3: false,
        shangga5: false,
        maxga3:false,
        fixga3:false,
        hunyise:true,
        sjzhuang: false,
        wuzi: false,
        zhuangxian: true,
        zyshangga: false,
    },
    coinData:{
        min:100,
        every:1,
        reduce:1,
        reduce_a:1,
        reduce_b:1,
    }
}
exports.erRen = {
    haveRoom:0,
    type: "hainanmj",
    jushu: 0,
    wanfa: 0,
    mjType: 2,
    tg:0,
    func:false,
    otherData: {
        buchi: false,
        budianpao: false,
        goujiao: false,
        haidibao: false,
        huahu: true,
        lianzhuang: true,
        ling: true,
        liuju: true,
        mogangfan: false,
        ready: false,
        shangga: true,
        shangga3: false,
        shangga5: false,
        maxga3:false,
        fixga3:false,
        hunyise:true,
        sjzhuang: false,
        wuzi: false,
        zhuangxian: true,
        zyshangga: false,
    },
    coinData:{
        min:100,
        every:1,
        reduce:1,
        reduce_a:1,
        reduce_b:1,
    }
}